{% set name = "flaky" %}
{% set version = "3.8.1" %}
{% set hash = "47204a81ec905f3d5acfbd61daeabcada8f9d4031616d9bcb0618461729699f5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6

test:
  imports:
    - flaky

about:
  home: https://github.com/box/flaky
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Plugin for nose or py.test that automatically reruns flaky tests.
  description: |
    Flaky is a plugin for nose or py.test that automatically reruns flaky
    tests.
  dev_url: https://github.com/box/flaky

extra:
  recipe-maintainers:
    - ccordoba12
    - rlaverde
