{% set name = "flaky" %}
{% set version = "3.7.0" %}
{% set hash = "3ad100780721a1911f57a165809b7ea265a7863305acb66708220820caf8aa0d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - flaky

about:
  home: https://github.com/box/flaky
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: Plugin for nose or py.test that automatically reruns flaky tests.
  description: |
    Flaky is a plugin for nose or py.test that automatically reruns flaky
    tests.
  dev_url: https://github.com/box/flaky

extra:
  recipe-maintainers:
    - ccordoba12
    - rlaverde
